### ISSUE TITLE
SQL Schema?

### ISSUE THREAD

**Issue by Topslakr** [dangoldin/health-stats#6]
Hello Dan,

Thanks for making this great idea public! I am working on importing my Apple Health stats into MySQL but with a totally blank SQL DB, the script keeps giving me errors. I'm trying to build out the columns, etc., it seems to want but I'm struggling.

Any chance you have/could make/could explain the schema I would need for this to populate properly?

I created 'health_stats' with three columns (type, datetime, value), but now I'm getting errors about incorrect integer values. Having something to create the structure, either within the script or as a .sql file, would be awesome. I'd be happy to do some leg work but without knowing what the script wants I'm not sure how to get started...

**Comment by dangoldin** [comment]
Ah good idea. I'll update the README in a bit but here's the schema:

```
CREATE TABLE `health_stats` (
  `datetime` datetime NOT NULL,
  `type` varchar(20) NOT NULL,
  `value` float NOT NULL,
  KEY `type` (`type`,`datetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by Topslakr** [comment]
Thanks! I really appreciate it.

It's loading data into the DB now, but with a 800MB XML file, it's taking it's time.

I submitted a pull request to, hopefully, save you a little time updating the Readme.

**Comment by dangoldin** [comment]
Yea - it's not the fastest but I just leave it running in the background. I don't see the PR yet but glad to merge it in.

**Comment by Topslakr** [comment]
Sorry. I'm still learning how to to use git.. I think it's there now?

**Comment by dangoldin** [comment]
This was great - thanks for the help!
